services: 
  kube-news:
    image: rof1966/kube-news-hml:${KUBENEWS_TAG:-latest}
    build: 
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"
    networks:
      - kubenews_net
    depends_on:
      - postgres
    environment:
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${POSTGRES_DB}
      DB_HOST: postgres # Nome do serviço que você atribuiu = postgres
      DB_PORT: 5432